### ISSUE TITLE
PosA and PosB differ from breakpoint locations specified in bedpe input

### ISSUE THREAD

**Issue by nriddiford** [J35P312/SplitVision#1]
Hi Jesper, 

First of all - thanks for writing this tool, I believe it could be very useful for the community! Are you planning on publishing it? 

I have a set of manually curated SV breakpoints from _Drosophila_ WGS that I want to analyse for micro homology/insertions etc. 

I am running your tool using the `--bed` option to specify breakpoints in a bedpe format. Here is my bedpe file `sample_breakpoints.bedpe` (in this case, it contains only 1 SV):

`X	1219691	X	1219821	BND:55`

(Note this format appears to be how `extract_splits` expects bedpe format, but differs from the bedpe format defined [here](https://bedtools.readthedocs.io/en/latest/content/general-usage.html#bedpe-format)).

Here is how I call your script: 

```
python splitvision.py \
  --analyse \
  --bed sample_breakpoints.bedpe \
  --bam sample.bam \
  --fa genome \
  --working_dir out_dir
```

The resulting file `sample.xls` contains: 

```
sampleID	variant_id	variant_type	split_reads	ChrA	PosA	OrientationA	repeatA	repeat_distanceA	snps/indelsA	snp_distance_A	ChrB	PosB	OrientationB	repeatB	repeat_distanceB	snps/indelsB	snp_distance_B	breakpoint_microhomology(bp)	breakpoint_microhomology(sequence)	insertions(bp)	insertions(sequence)	lengthA	lengthB	contig_length	regionA_sequence	regionB_sequence	contig_sequence
B241R43	0	BND:55	4	X	1220226	-			X-1220205-G-A	21	X	1220062	+			none	> 100	10	ACGCTCCCGC	0		60	51	101	ACGCTCCCGCCCAAGAACCGGTACAAAAACAGCAATCGCGGTGGAGCCATCGACAGCAGC	GCGGGAGCGTCCGCGGAGGGCTGAGACCTTGGACAATGCACGCAGCTACAT	ATGTAGCTGCGTGCATTGTCCAAGGTCTCAGCCCTCCGCGGACGCTCCCGCCCAAGAACCGGTACAAAAACAGCAATCGCGGTGGAGCCATCGACAGCAGC
```

Where `PosA`: `1220226` `PosB`: `1220062` - different from the breakpoints I provided in the bedpe file. Is this expected behaviour? 

Many thanks,

Nick

**Comment by J35P312** [comment]
Hello there!
Thanks! The tool is kinda published in:

Replicative and non-replicative mechanisms in the formation of clustered CNVs are indicated by whole genome characterization. Nazaryan-Petersen et al.

However, the algorithm is hidden in supplementary methods, and the paper does not really focus on the tool.
I'm a PhD student, and will graduate in a couple of months, as such, this software will not be published, and not maintained as well as it deserves.

The breakpoints of the excel file may differ from those in the bed file: SplitVision will extract split-reads (supplementary alignments), and generate a consensus read from these split-reads. The consensus read is aligned to the reference genome. The breakpoint
positions, and statistics reported in excel file are based on the alignment of that consensus read.

This usually works well, but may be problematic if the breakpoint regions are too repetitive, or if the read-length is too short (I have only tested 151 bp reads).

In this case, I think the breakpoints differ too much for such a small variant. I would recommend rerunning with a smaller window size:

python splitvision.py \
  --analyse \
  --bed sample_breakpoints.bedpe \
  --bam sample.bam \
  --fa genome \
  --working_dir out_dir
  --padding 50

Here, padding is the distance (basepairs) that splitvision will search for splitreads. per default this distance is set to 1000. This distance needs to be smaller than the SV being analysed.

Feel free to try SplitVision, I must say that the tool is a bit shaky, it would need more polishing, and a better documentation. I hope to improve it further, but I'm not sure if I have time to do so.

Good luck! Hope you get splitvision to run, or that you find another tool that works for you ! =P
